DROP DATABASE IF EXISTS DB_NAME;
CREATE DATABASE DB_NAME;
USE DB_NAME;

CREATE TABLE USERS(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nom VARCHAR (100) NOT NULL,
    Prenom VARCHAR (225) NOT NULL,
    UserRole ENUM ('admin','user')
);

