DROP TABLE IF EXISTS Achat;
DROP TABLE IF EXISTS Caisse;
DROP TABLE IF EXISTS Produit;
DROP TABLE IF EXISTS User;

CREATE TABLE Produit(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    designation TEXT,
    prix REAL NOT NULL,
    stock INTEGER NOT NULL
);

CREATE TABLE Caisse(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    numero INTEGER NOT NULL
);

CREATE TABLE Achat(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    id_caisse INTEGER NOT NULL,
    id_produit INTEGER NOT NULL,
    client TEXT NOT NULL,
    quantite INTEGER NOT NULL,
    montant REAL NOT NULL,
    date_achat DATETIME NOT NULL,
    FOREIGN KEY (id_caisse) REFERENCES Caisse(id),
    FOREIGN KEY (id_produit) REFERENCES Produit(id)
);

CREATE TABLE User(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    caissier TEXT NOT NULL,
    password TEXT NOT NULL
);